# Generated by Django 5.2.6 on 2025-09-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="stray_sender_api.user",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("desc", models.TextField(blank=True)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("picture_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_threads",
                        to="stray_sender_api.user",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_threads",
                        to="stray_sender_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("downvotes", models.PositiveIntegerField(default=0)),
                ("score", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="stray_sender_api.user",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="stray_sender_api.user",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="stray_sender_api.thread",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("up", "Upvote"), ("down", "Downvote")], max_length=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="stray_sender_api.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stray_sender_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_of",
                        to="stray_sender_api.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships",
                        to="stray_sender_api.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="stray_sende_user_id_d4beac_idx"
                    ),
                    models.Index(
                        fields=["friend"], name="stray_sende_friend__709653_idx"
                    ),
                ],
                "unique_together": {("user", "friend")},
            },
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["initiator"], name="stray_sende_initiat_cfb793_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["target"], name="stray_sende_target__4ebb84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["updated_at"], name="stray_sende_updated_69be6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["created_at"], name="stray_sende_created_e12507_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["-current_streak"], name="stray_sende_current_5d08a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "-created_at"], name="stray_sende_thread__46442e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender"], name="stray_sende_sender__0b548e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["target"], name="stray_sende_target__587883_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-score"], name="stray_sende_score_6488e5_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-created_at"], name="stray_sende_created_361f7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["message"], name="stray_sende_message_61fc64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["user"], name="stray_sende_user_id_ccce08_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "message")},
        ),
    ]
