# Generated by Django 5.2.6 on 2025-09-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stray_sender_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
